# Generated by Django 4.1.2 on 2022-10-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerRecord",
            fields=[
                ("oplusid", models.UUIDField(primary_key=True, serialize=False)),
                ("partner_name", models.CharField(max_length=200)),
                ("mrn", models.CharField(max_length=200)),
                ("doctor_notes", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
