# Generated by Django 4.1.2 on 2022-10-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentFactor",
            fields=[
                ("oplusid", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalImage",
            fields=[
                ("oplusid", models.UUIDField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="partnerrecord",
            name="environment_factors",
            field=models.ForeignKey(
                default=1,
                max_length=200,
                on_delete=django.db.models.deletion.CASCADE,
                to="partner_records.environmentfactor",
            ),
            preserve_default=False,
        ),
    ]
