# Generated by Django 4.1.2 on 2022-10-12 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("partner_records", "0003_partnerrecord_medical_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentfactor",
            name="oplusid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="medicalimage",
            name="oplusid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="partnerrecord",
            name="oplusid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
