# Generated by Django 4.1.2 on 2022-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("partner_records", "0004_alter_environmentfactor_oplusid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorNotes",
            fields=[
                (
                    "oplusid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Doctor's notes",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Doctor's notes",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "oplusid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="environmentfactor",
            name="description",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Doctor's notes",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partnerrecord",
            name="patient",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="partner_records.patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="partnerrecord",
            name="doctor_notes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_notes",
                to="partner_records.doctornotes",
            ),
        ),
    ]
