# Generated by Django 4.1.2 on 2022-10-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner_records", "0005_doctornotes_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerrecord",
            name="doctor_notes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_notes",
                to="partner_records.doctornotes",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrecord",
            name="environment_factors",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_factors",
                to="partner_records.environmentfactor",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrecord",
            name="medical_images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_images",
                to="partner_records.medicalimage",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrecord",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partner_records.patient",
            ),
        ),
    ]
