# Generated by Django 4.1.2 on 2022-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="bin",
            field=models.CharField(default="000-0000", max_length=200),
        ),
    ]
